### ISSUE TITLE
Unhelpful logging messages

### ISSUE THREAD

**Issue by geoghegk** [IBM/transformation-advisor-sdk#35] opened 2020-03-23 10:55 UTC
**Describe the bug**
There are several log files (ta_util.log.X) with nothing but the following entry:
2020-03-16 04:51:22 DEBUG CompiledPath:47 - Evaluating path: @['targetMember']
This might be intended behavior - but the log on its own is not very useful. If it was accompanied by a "Evaluation successful" or something like that it would be more useful.

I can see this message in a sample collector, but in the IIS collector, I see 10 log files with nothing but this entry in them. Maybe due to the number of issues being detected in the real IIS plugin - but comment on usefulness still stands.

**To Reproduce**
Can be seen in the sample datacollector at small scale. 

**Expected behavior**
Useful log messages. 

**Screenshots**
![Screenshot 2020-03-20 at 10 46 15](https://user-images.githubusercontent.com/18310573/77309501-b011d480-6cf4-11ea-9e27-7dc024788c66.png)

**Desktop (please complete the following information):**
 - OS: na
 - Browser na
 - Version na

**Additional context**

**Comment by transformationAdvisor-sdk** [comment] 2020-05-25 16:10
@geoghegk ,  Cannot reproduce this problem in the latest SDK when run the sample plug-in.
Is this related to old TA SDK before move to current repo?

**Comment by geoghegk** [comment] 2020-05-26 12:52
@transformationAdvisor-sdk yes, this if from older SDK. Looks like its gone now. Maybe the json-path upgrade fixed it. I'm happy to close this out.

**Comment by transformationAdvisor-sdk** [comment] 2020-05-27 15:03
Fixed,  close it

**Closed by transformationAdvisor-sdk** 2020-05-27 15:03 UTC
Labels: bug
